const now = new Date().toISOString();

export const seedRows = [
  {
    issueKey: "XFN-1001",
    scrumTeam: "Creative Insights",
    alliGroup: "Insights",
    sprintIteration: "2026-06-08",
    productGoal: "Improve cross-campaign insights access for planning teams.",
    sprintGoal:
      "Meta aggregated asset profile consumable for all owning teams to improve cross-campaign views.",
    goalMet: true,
    confidence: "High",
    health: "On Track",
    riskLevel: "Medium",
    risks: ["Meta SDK rate limits"],
    needs: ["Creative Engineering blob access", "Meta repo support"],
    impacts: ["Manual extraction still required for a subset of Meta assets"],
    progress:
      "JIRA-2891 has been approved and verified. Manual extraction is down compared to last sprint.",
  },
  {
    issueKey: "XFN-1002",
    scrumTeam: "Business Insights",
    alliGroup: "Insights",
    sprintIteration: "2026-06-08",
    productGoal: "Tighten prompt setup quality for priority business teams.",
    sprintGoal: "Enhance setup prompt for generated business insight workflows.",
    goalMet: false,
    confidence: "Medium",
    health: "At Risk",
    riskLevel: "High",
    risks: ["PTO next week", "Prompt QA coverage still incomplete"],
    needs: ["Reviewer availability from Customer group"],
    impacts: ["Delayed validation could push setup wizard rollout"],
    progress: "Prompt draft is working, but validation coverage is behind plan.",
  },
  {
    issueKey: "XFN-1003",
    scrumTeam: "Audience Planner",
    alliGroup: "Actions",
    sprintIteration: "2026-06-08",
    productGoal: "Give planners faster reach and targeting checks.",
    sprintGoal: "Implement Snapshot reach current-state readout.",
    goalMet: true,
    confidence: "High",
    health: "On Track",
    riskLevel: "Low",
    risks: [],
    needs: [],
    impacts: [],
    progress: "Snapshot reach current-state readout is implemented and ready for review.",
  },
  {
    issueKey: "XFN-1004",
    scrumTeam: "Data Library",
    alliGroup: "Data",
    sprintIteration: "2026-06-08",
    productGoal: "Expand reliable campaign and commerce datasets.",
    sprintGoal: "Add new data tables for Prime Day reporting.",
    goalMet: true,
    confidence: "Medium",
    health: "At Risk",
    riskLevel: "High",
    risks: ["Walmart data erroring"],
    needs: ["Commerce data owner sign-off"],
    impacts: ["Prime Day dashboards may show partial coverage until Walmart ingest stabilizes"],
    progress: "Prime Day tables are added. Walmart ingest is the active blocker.",
  },
  {
    issueKey: "XFN-1005",
    scrumTeam: "GenAaaS",
    alliGroup: "Core",
    sprintIteration: "2026-06-08",
    productGoal: "Improve stability of shared generative services.",
    sprintGoal: "Dual-SIM optimizations and stability pass.",
    goalMet: false,
    confidence: "Low",
    health: "At Risk",
    riskLevel: "High",
    risks: ["OOM risk"],
    needs: ["USA API support"],
    impacts: ["Shared services may be unstable under larger synthetic workloads"],
    progress: "Optimization work is underway, but memory pressure is still above target.",
  },
].map((row) => ({
  ...row,
  jiraUrl: "",
  confluenceUrl: "",
  source: "seed",
  rawJson: {},
  updatedAt: now,
  lastSyncedAt: now,
}));
